### ISSUE TITLE
ERROR READING SENSOR HEADER

### ISSUE THREAD

**Issue by WafaAbid1** [RicardoRagel/arduimu-ros-driver#1]
When running roslaunch arduimu_ros_driver arduimu_ros_driver.launch use_arduimu_rpy:=false, I get the error  ERROR READING SENSOR HEADER.
Any idea how to fix it?

**Comment by RicardoRagel** [comment]
Hi @WafaAbid1 

First, let my apologise becouse I don't have any device to test this program, so I can not try to replicate the issue here.

In anycase, let's try to check what is happening with your device. Assuming it is connected correctly (you can see the device at `/dev/arduimu`) and you are receiving data, you can check this received data uncommenting the line:
https://github.com/RicardoRagel/arduimu-ros-driver/blob/62ed9109b042c4760e4833562c8c6eb502c96fb9/src/arduimu_sensors.cpp#L27
 and compiling again.

Check also the comments in the header of that file:

```cpp
/*!
 * 9DOF ArduIMU node - Ricardo Ragel
 * ---------------------------------
 * 
 * This node read the IMU sensors (accel, gyros, magnet) output in format:
 * 	#M-C=17.83,-25.33,-42.83
 * 	#G-C=-32.00,13.00,-3.00
 *	#A-C=-73.73,-174.08,160.77
 * 
 * and publish them through the ROS topic "/arduimu/accel", "/arduimu/gyros", /arduimu/magne"
 * 
 * Serial port configuration must be 115200, 8N1, NOR
 */
```
So the data that you are receiving should have that format. In case it is not the same format, perhaps you are using a different device firmware than the one expected by this package.

Best regards and good luck!

**Comment by WafaAbid1** [comment]
Thank you! Do you think we can get the imu frequency to more than 175 hz?

**Comment by RicardoRagel** [comment]
Sincerely, I don't know. You can search for this information in the board firmware repo: https://github.com/Razor-AHRS/razor-9dof-ahrs
